// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxocwtjeedyzgylgciwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4b2N3dGplZWR5emd5bGdjaXdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDU1NzYsImV4cCI6MjA2NTIyMTU3Nn0.cBlQB1NYr3G7VSQCaUtfg0k-JWSGBWaC_ioNQ8rso1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);